### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [mozilla/about-home-piano-snippet#1]
The repo is public, but it's not easy to find out how I'm allowed to use or share the code. 

Could you add a LICENSE file to make it easier for users to understand how you'd like it to be used? 

http://choosealicense.com/ might be helpful here. 

Thanks!

**Comment by glogiotatidis** [comment]
Good point. btw @Osmose should we move data from this repo to mozilla/snippets which also has a license?

**Comment by glogiotatidis** [comment]
Moved, updated readme. 

New repository has a license too. Thanks for reporting @edunham
